/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    Analytics: () => import('#controllers/admin/analytics_controller'),
    Auth: () => import('#controllers/admin/auth_controller'),
    Dashboard: () => import('#controllers/admin/dashboard_controller'),
    Roles: () => import('#controllers/admin/roles_controller'),
    Users: () => import('#controllers/admin/users_controller'),
  },
  Debug: () => import('#controllers/debug_controller'),
  EmbeddedWallet: () => import('#controllers/embedded_wallet_controller'),
  Health: () => import('#controllers/health_controller'),
  Notify: () => import('#controllers/notify_controller'),
  Resolve: () => import('#controllers/resolve_controller'),
  Webhook: () => import('#controllers/webhook_controller'),
}
