/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AdminUserSchema extends BaseModel {
  static $columns = [
    'id',
    'fullName',
    'email',
    'password',
    'role',
    'createdAt',
    'updatedAt',
  ] as const
  $columns = AdminUserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare fullName: string | null
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ColursBankAccountSchema extends BaseModel {
  static $columns = [
    'id',
    'phoneNumber',
    'colursId',
    'holderName',
    'documentType',
    'documentNumber',
    'accountNumber',
    'accountType',
    'bankId',
    'bankName',
    'countryCode',
    'isDefault',
    'createdAt',
  ] as const
  $columns = ColursBankAccountSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare phoneNumber: string
  @column()
  declare colursId: string
  @column()
  declare holderName: string
  @column()
  declare documentType: string
  @column()
  declare documentNumber: string
  @column()
  declare accountNumber: string
  @column()
  declare accountType: string
  @column()
  declare bankId: number
  @column()
  declare bankName: string | null
  @column()
  declare countryCode: string
  @column()
  declare isDefault: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class ColursKycSchema extends BaseModel {
  static $columns = [
    'phoneNumber',
    'fullname',
    'idType',
    'idNumber',
    'email',
    'colursUserId',
    'counterpartyId',
    'kycLevel',
    'kycStatus',
    'createdAt',
    'updatedAt',
  ] as const
  $columns = ColursKycSchema.$columns
  @column()
  declare phoneNumber: string
  @column()
  declare fullname: string | null
  @column()
  declare idType: string | null
  @column()
  declare idNumber: string | null
  @column()
  declare email: string | null
  @column()
  declare colursUserId: number | null
  @column()
  declare counterpartyId: string | null
  @column()
  declare kycLevel: number
  @column()
  declare kycStatus: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ConversationContextSchema extends BaseModel {
  static $columns = ['phoneNumber', 'messages', 'updatedAt'] as const
  $columns = ConversationContextSchema.$columns
  @column()
  declare phoneNumber: string
  @column()
  declare messages: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExportAuditLogSchema extends BaseModel {
  static $columns = ['id', 'attemptId', 'event', 'phoneHash', 'walletAddress', 'createdAt'] as const
  $columns = ExportAuditLogSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare attemptId: string
  @column()
  declare event: string
  @column()
  declare phoneHash: string
  @column()
  declare walletAddress: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
}

export class OfframpOrderSchema extends BaseModel {
  static $columns = [
    'id',
    'phoneNumber',
    'externalId',
    'colursQuoteId',
    'colursMovementId',
    'bankAccountId',
    'amountUsdc',
    'amountCop',
    'exchangeRate',
    'status',
    'error',
    'createdAt',
    'updatedAt',
    'pullTxHash',
    'polledAt',
    'pollCount',
  ] as const
  $columns = OfframpOrderSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare phoneNumber: string
  @column()
  declare externalId: string
  @column()
  declare colursQuoteId: string | null
  @column()
  declare colursMovementId: string | null
  @column()
  declare bankAccountId: number
  @column()
  declare amountUsdc: string
  @column()
  declare amountCop: string | null
  @column()
  declare exchangeRate: string | null
  @column()
  declare status: string
  @column()
  declare error: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare pullTxHash: string | null
  @column.dateTime()
  declare polledAt: DateTime | null
  @column()
  declare pollCount: number
}

export class OnrampOrderSchema extends BaseModel {
  static $columns = [
    'id',
    'phoneNumber',
    'externalId',
    'colursPaymentId',
    'method',
    'amountCop',
    'amountUsdt',
    'depositAddress',
    'idempotencyKey',
    'paymentLink',
    'trackingKey',
    'status',
    'lifiTxHash',
    'usdcReceived',
    'error',
    'createdAt',
    'updatedAt',
    'polledAt',
    'pollCount',
  ] as const
  $columns = OnrampOrderSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare phoneNumber: string
  @column()
  declare externalId: string
  @column()
  declare colursPaymentId: string | null
  @column()
  declare method: string
  @column()
  declare amountCop: string
  @column()
  declare amountUsdt: string | null
  @column()
  declare depositAddress: string
  @column()
  declare idempotencyKey: string | null
  @column()
  declare paymentLink: string | null
  @column()
  declare trackingKey: string | null
  @column()
  declare status: string
  @column()
  declare lifiTxHash: string | null
  @column()
  declare usdcReceived: string | null
  @column()
  declare error: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.dateTime()
  declare polledAt: DateTime | null
  @column()
  declare pollCount: number
}

export class ParseLogSchema extends BaseModel {
  static $columns = [
    'id',
    'messageId',
    'phoneNumber',
    'parseSource',
    'intent',
    'model',
    'promptTokens',
    'completionTokens',
    'latencyMs',
    'status',
    'detectedLanguage',
    'createdAt',
    'matchedPhrase',
  ] as const
  $columns = ParseLogSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare messageId: string
  @column()
  declare phoneNumber: string | null
  @column()
  declare parseSource: string
  @column()
  declare intent: string
  @column()
  declare model: string | null
  @column()
  declare promptTokens: number | null
  @column()
  declare completionTokens: number | null
  @column()
  declare latencyMs: number
  @column()
  declare status: string
  @column()
  declare detectedLanguage: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare matchedPhrase: string | null
}

export class PendingInviteSchema extends BaseModel {
  static $columns = [
    'id',
    'senderPhone',
    'recipientPhone',
    'status',
    'createdAt',
    'expiresAt',
    'claimedAt',
    'notifiedAt',
  ] as const
  $columns = PendingInviteSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare senderPhone: string
  @column()
  declare recipientPhone: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare expiresAt: bigint | number
  @column()
  declare claimedAt: bigint | number | null
  @column()
  declare notifiedAt: bigint | number | null
}

export class PhoneRegistrySchema extends BaseModel {
  static $columns = [
    'phoneNumber',
    'cdpWalletName',
    'walletAddress',
    'createdAt',
    'lastActivity',
    'dailySpent',
    'lastResetDate',
    'spendPermissionHash',
    'dailyLimit',
    'permissionCreatedAt',
  ] as const
  $columns = PhoneRegistrySchema.$columns
  @column()
  declare phoneNumber: string
  @column()
  declare cdpWalletName: string
  @column()
  declare walletAddress: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare lastActivity: bigint | number
  @column()
  declare dailySpent: string
  @column()
  declare lastResetDate: string
  @column()
  declare spendPermissionHash: string | null
  @column()
  declare dailyLimit: string | null
  @column()
  declare permissionCreatedAt: bigint | number | null
}

export class TransactionSchema extends BaseModel {
  static $columns = ['id', 'createdAt', 'updatedAt'] as const
  $columns = TransactionSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserContactSchema extends BaseModel {
  static $columns = [
    'id',
    'ownerPhone',
    'alias',
    'aliasDisplay',
    'targetPhone',
    'source',
    'createdAt',
  ] as const
  $columns = UserContactSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ownerPhone: string
  @column()
  declare alias: string
  @column()
  declare aliasDisplay: string
  @column()
  declare targetPhone: string
  @column()
  declare source: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
}

export class UserPreferenceSchema extends BaseModel {
  static $columns = [
    'phoneNumber',
    'preferredLanguage',
    'updatedAt',
    'emailEncrypted',
    'emailHash',
    'emailVerified',
    'emailVerifiedAt',
    'phoneVisible',
    'blocked',
    'tosAcceptedAt',
    'tosVersion',
    'emailNudgeSentAt',
    'setupNotifiedAt',
  ] as const
  $columns = UserPreferenceSchema.$columns
  @column()
  declare phoneNumber: string
  @column()
  declare preferredLanguage: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare emailEncrypted: string | null
  @column()
  declare emailHash: string | null
  @column()
  declare emailVerified: boolean
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare phoneVisible: boolean
  @column()
  declare blocked: boolean
  @column.dateTime()
  declare tosAcceptedAt: DateTime | null
  @column()
  declare tosVersion: string | null
  @column.dateTime()
  declare emailNudgeSentAt: DateTime | null
  @column.dateTime()
  declare setupNotifiedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'id',
    'phoneNumber',
    'cdpWalletName',
    'walletAddress',
    'status',
    'kycStatus',
    'kycLevel',
    'displayName',
    'language',
    'notificationsEnabled',
    'isPublic',
    'dailyLimit',
    'transactionLimit',
    'dailySpent',
    'lastResetDate',
    'createdAt',
    'updatedAt',
    'lastActivity',
  ] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare phoneNumber: string
  @column()
  declare cdpWalletName: string
  @column()
  declare walletAddress: string
  @column()
  declare status: string | null
  @column()
  declare kycStatus: string | null
  @column()
  declare kycLevel: number | null
  @column()
  declare displayName: string | null
  @column()
  declare language: string | null
  @column()
  declare notificationsEnabled: boolean | null
  @column()
  declare isPublic: boolean | null
  @column()
  declare dailyLimit: string | null
  @column()
  declare transactionLimit: string | null
  @column()
  declare dailySpent: string | null
  @column.dateTime()
  declare lastResetDate: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare lastActivity: DateTime | null
}

export class WebSendLogSchema extends BaseModel {
  static $columns = [
    'id',
    'phoneHash',
    'walletAddress',
    'toAddress',
    'amount',
    'txHash',
    'createdAt',
  ] as const
  $columns = WebSendLogSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare phoneHash: string
  @column()
  declare walletAddress: string
  @column()
  declare toAddress: string
  @column()
  declare amount: string
  @column()
  declare txHash: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
}
