/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AdminUserSchema extends BaseModel {
  static $columns = [
    'id',
    'fullName',
    'email',
    'password',
    'role',
    'createdAt',
    'updatedAt',
  ] as const
  $columns = AdminUserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare fullName: string | null
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ConversationContextSchema extends BaseModel {
  static $columns = ['phoneNumber', 'messages', 'updatedAt'] as const
  $columns = ConversationContextSchema.$columns
  @column()
  declare phoneNumber: string
  @column()
  declare messages: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExportAuditLogSchema extends BaseModel {
  static $columns = ['id', 'attemptId', 'event', 'phoneHash', 'walletAddress', 'createdAt'] as const
  $columns = ExportAuditLogSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare attemptId: string
  @column()
  declare event: string
  @column()
  declare phoneHash: string
  @column()
  declare walletAddress: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
}

export class ParseLogSchema extends BaseModel {
  static $columns = [
    'id',
    'messageId',
    'phoneNumber',
    'parseSource',
    'intent',
    'model',
    'promptTokens',
    'completionTokens',
    'latencyMs',
    'status',
    'detectedLanguage',
    'createdAt',
    'matchedPhrase',
  ] as const
  $columns = ParseLogSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare messageId: string
  @column()
  declare phoneNumber: string | null
  @column()
  declare parseSource: string
  @column()
  declare intent: string
  @column()
  declare model: string | null
  @column()
  declare promptTokens: number | null
  @column()
  declare completionTokens: number | null
  @column()
  declare latencyMs: number
  @column()
  declare status: string
  @column()
  declare detectedLanguage: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare matchedPhrase: string | null
}

export class PendingInviteSchema extends BaseModel {
  static $columns = [
    'id',
    'senderPhone',
    'recipientPhone',
    'status',
    'createdAt',
    'expiresAt',
    'claimedAt',
    'notifiedAt',
  ] as const
  $columns = PendingInviteSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare senderPhone: string
  @column()
  declare recipientPhone: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare expiresAt: bigint | number
  @column()
  declare claimedAt: bigint | number | null
  @column()
  declare notifiedAt: bigint | number | null
}

export class PhoneRegistrySchema extends BaseModel {
  static $columns = [
    'phoneNumber',
    'cdpWalletName',
    'walletAddress',
    'createdAt',
    'lastActivity',
    'dailySpent',
    'lastResetDate',
    'spendPermissionHash',
    'dailyLimit',
    'permissionCreatedAt',
  ] as const
  $columns = PhoneRegistrySchema.$columns
  @column()
  declare phoneNumber: string
  @column()
  declare cdpWalletName: string
  @column()
  declare walletAddress: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare lastActivity: bigint | number
  @column()
  declare dailySpent: string
  @column()
  declare lastResetDate: string
  @column()
  declare spendPermissionHash: string | null
  @column()
  declare dailyLimit: string | null
  @column()
  declare permissionCreatedAt: bigint | number | null
}

export class UserContactSchema extends BaseModel {
  static $columns = [
    'id',
    'ownerPhone',
    'alias',
    'aliasDisplay',
    'targetPhone',
    'source',
    'createdAt',
  ] as const
  $columns = UserContactSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ownerPhone: string
  @column()
  declare alias: string
  @column()
  declare aliasDisplay: string
  @column()
  declare targetPhone: string
  @column()
  declare source: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
}

export class UserPreferenceSchema extends BaseModel {
  static $columns = [
    'phoneNumber',
    'preferredLanguage',
    'updatedAt',
    'emailEncrypted',
    'emailHash',
    'emailVerified',
    'emailVerifiedAt',
    'phoneVisible',
    'blocked',
    'tosAcceptedAt',
    'tosVersion',
    'emailNudgeSentAt',
    'setupNotifiedAt',
  ] as const
  $columns = UserPreferenceSchema.$columns
  @column()
  declare phoneNumber: string
  @column()
  declare preferredLanguage: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare emailEncrypted: string | null
  @column()
  declare emailHash: string | null
  @column()
  declare emailVerified: boolean
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare phoneVisible: boolean
  @column()
  declare blocked: boolean
  @column.dateTime()
  declare tosAcceptedAt: DateTime | null
  @column()
  declare tosVersion: string | null
  @column.dateTime()
  declare emailNudgeSentAt: DateTime | null
  @column.dateTime()
  declare setupNotifiedAt: DateTime | null
}

export class WalletAliasSchema extends BaseModel {
  static $columns = ['address', 'ownerPhone'] as const
  $columns = WalletAliasSchema.$columns
  @column()
  declare address: string
  @column()
  declare ownerPhone: string
}

export class WebSendLogSchema extends BaseModel {
  static $columns = [
    'id',
    'phoneHash',
    'walletAddress',
    'toAddress',
    'amount',
    'txHash',
    'createdAt',
  ] as const
  $columns = WebSendLogSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare phoneHash: string
  @column()
  declare walletAddress: string
  @column()
  declare toAddress: string
  @column()
  declare amount: string
  @column()
  declare txHash: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
}
