# .nightcrawler/config.sh for sippy
# WARNING: Commands are executed via eval. Only edit if you trust the content.
# Generated by: nightcrawler init

BUILD_CMD="pnpm turbo build"
TEST_CMD="pnpm turbo test"
INSTALL_CMD="pnpm install"
DEPS_CHECK="test -d node_modules"
TOOLS=" node pnpm turbo"
TOOLS_ALLOW=" node pnpm turbo"
BASE_BRANCH="nightcrawler/otp"
TELEGRAM_THREAD_ID=""
